### PR TITLE
Feat/add sidenav

### PR DESCRIPTION
**Pull request by markkovari**

### CODE REVIEW

**Comment by AnnaUgrai** [comment]
Hi, I'm not sure what the error is here.
How should we resolve it?

**Comment by markkovari** [comment]
I'll create more smaller PRs instead of this, kist like with the other one.

**Comment by AnnaUgrai** [comment]
So, we had small pr-s and what should be the faith of this one?

**Comment by markkovari** [comment]
@AnnaUgrai well really good question, not sure if we covered every change or if we even want, but after that we should just close this one.

**Comment by AnnaUgrai** [comment]
I lost track too, but I think what we wanted to add is already added, right?
I would close this one

**Comment by markkovari** [comment]
Discussed with @AnnaUgrai, closing this one, since implemented with other PRs.

**Pull request closed without merging**
