### PR TITLE
feat: add checkstyle linter locally before run too

### PR DESCRIPTION
**Pull request by markkovari**
Our linter - watchdog is biting in our hands. We should do that more often to make this process less inconvenient. We should not even be able to build/test or other scripts with errors/warnings.

How to reproduce locally:

follow to instructions how to install (I created a script for that)

aaaaand that should be it, you won't be able to commit invalid code.

https://www.youtube.com/watch?v=d70a8PXbrb8

### CODE REVIEW

**Review by carlos-ponton — APPROVED** [review]
Nice! This will help us to minimize the commits that we create to make reviewdog happy.

**Review by AnnaUgrai — APPROVED** [review]
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcNj38cgjNTiMsKyxGoqRIInPXE4J9ilQYXg&s

**Review by Hsbalazs — APPROVED** [review]
Nice!

**Comment by markkovari** [comment]
Maybe extend it with precommit hook to prevent it even to commit bad code.

**Comment by markkovari** [comment]
Not the same as watchdog.

**Pull request closed without merging**
