### PR TITLE
Chore/add test coverage restrictions

### PR DESCRIPTION
**Pull request by markkovari**

### CODE REVIEW

**Comment by Hsbalazs** [comment]
image

WOW!

**Comment by markkovari** [comment]
@Hsbalazs well yes, I deleted a bunch of things. But added some, we've been behind with a bunch of tests for example.

**Comment by carlos-ponton** [comment]
I bet @AnnaUgrai is loving these test coverage restrictions.  

image

**Comment by markkovari** [comment]
I will not tell anyone that it was her idea, I can get in trouble for that.

**Comment by AnnaUgrai** [comment]
Traitor 😂🤓

**Review by Hsbalazs — APPROVED** [review]

**Pull request merged**
