### PR TITLE
test(Login) FE send HTTP request on filled fields when submit, 

### PR DESCRIPTION
**Pull request by ramesz6**
and does not send, when email field is not filled

### CODE REVIEW

**Comment by markkovari** [comment]
image

**Comment by markkovari** [comment]
image

**Comment by markkovari** [comment]
image

**Review by Hsbalazs — APPROVED** [review]

**Review by markkovari — CHANGES_REQUESTED** [review]
image

**Review by markkovari — APPROVED** [review]

**Pull request merged**
