### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by carlos-ponton**
I added a couple of tests for the userService.

### CODE REVIEW

**Comment by markkovari** [comment]
I generally recommend you to use a bit more descriptive branch-names. First of all we cannot create after this any after that like `tests/anything-else` other than that we should somewhat treat our PRs/branches/commit messages as communication, not just a necessary somthing.

**Comment by carlos-ponton** [comment]
@markkovari I didn't do those changes, that is what I don't understand. Maybe those were the changes you made on saturday? I pulled to get changes you made on SCRUM-46, I guess that they are shown here because I created a pull request before a pull request for SCRUM-46?

**Comment by markkovari** [comment]
Yeah, you have the changes from the 46 too, but those are not really related with these tests.

**Comment by carlos-ponton** [comment]
I think I will wait for our session to talk about this and and decide what to do next, because I don't understand why the changes are reflected on the tests branch as it was me who did them.

**Comment by AnnaUgrai** [comment]
> I think I will wait for our session to talk about this and and decide what to do next, because I don't understand why the changes are reflected on the tests branch as it was me who did them.

Carlos, in this case, do you want me to push my code to SCRUM-46, or only after discussion?

**Comment by carlos-ponton** [comment]
@AnnaUgrai You can push it

**Comment by AnnaUgrai** [comment]
Okay, I just pushed it

**Pull request closed without merging**
