### PR TITLE
Add User model and UserRepository

### PR DESCRIPTION
**Pull request by carlos-ponton**
Hey guys, can you review this and tell me if there is something I missed to include?

### CODE REVIEW

**Comment by ramesz6** [comment]
Hey! Shouldn't we need getters and setter for the model? just asking, i'm not sure

**Comment by carlos-ponton** [comment]
> Hey! Shouldn't we need getters and setter for the model? just asking, i'm not sure

@Getter and @Setter are included inside @Data

**Comment by markkovari** [comment]
And you have some errors which are being described in the checks too. Not sure why it is not added to the code tho.

**Review by markkovari — APPROVED** [review]
image

**Review by AnnaUgrai — APPROVED** [review]
image

**Pull request merged**
